### PR TITLE
GitHub Actions + Yarn

### PR DESCRIPTION
**Pull request by p2kmgcl**
This is a test to use GitHub actions instead of Travis. The benefits of moving to GitHub's ci (for now) are:

- Most stable Windows build (as suggested by @wincent)
- More specific checks: separate linting and building from testing, which finally reduces the overall check time.

__ToDo 1__: still need to check if caching (to speed up testing) `node_modules` is something that should be doing, because although it looks like a good idea I've found in [GitHub's cache action docs](https://github.com/actions/cache/blob/main/examples.md#node---npm) that caching `node_modules` with `npm` may result in unstable builds (maybe we should switch to yarn :shrug:, but who knows).

__ToDo 2__: we definitely need to get some extra permissions on this repo, I need to request _someone_ to remove the expected "travis run" that blocks this run :disappointed:

### CODE REVIEW

**Comment by wincent** [comment]
> maybe we should switch to yarn

Yes! We moved to Yarn everywhere in the Frontend Infra repos and it got rid of a lot of headaches for us (not even talking about CI).

> we definitely need to get some extra permissions on this repo, I need to request _someone_ to remove the expected "travis run" that blocks this run 😞

I don't think you can get elevated privs. Just open an `IS` ticket in JIRA; they usually do whatever you ask within a day (they're in the US, so it often happens overnight).

**Comment by p2kmgcl** [comment]
Ok, you convinced me :sweat_smile:,  NPM replaced :partying_face: 
I'm going to open the Jira ticket :smile:

**Comment by p2kmgcl** [comment]
:thinking: build is failing now, maybe I've accidentally updated Typescript

**Comment by p2kmgcl** [comment]
D: still having fixWinEPERM issues, I'm going to check yeoman-test changelog and see if we can do something with an upgrade

**Comment by p2kmgcl** [comment]
Still failing... I'll investigate this another day

**Review by victorg1991 — APPROVED** [review]

**Pull request merged**
