### PR TITLE
feat: enable scss files (#19)

### PR DESCRIPTION
**Pull request by faragos**
Hey,

I implemented the scss -> css preprocessing. I know the ticket ( #19 ) is about a custom workflow for everything, but I don't have the time, knowledge and needs to implement everything by myself. I'm also new with Typescript so please be kind 😃

With my changes the compress task generates a css file in the fragment folder. This way it works without changing everything.

I added a test and also changed the generator for templates.

A big problem I found while implementing is that the configuration and the final projectcontent gets loaded at the same time. Because of that I couldn't use the getProjectContent instead I needed to parse the 'fragments.json' seperatly. Otherwise the .css would have been empty.

I also needed to change the typecheck command, because it didn't work on Windows 😕 Now it should work on both OS.

The includePaths in the scss config is useful to provide the theme-scss-variables for example which will be in a different directory for sure.

I'm open for any improvements. 😃

### CODE REVIEW

**Comment by faragos** [comment]
Any update? Will this ever be merged or should I create my own Repo and npm-module? 😕

**Comment by victorg1991** [comment]
Hey @faragos sorry for the delay answering, thanks a lot for your effort. We've been pretty busy working on the 7.3 release. Your PR looks great, once the release is done, we'll come back to your pr to work towards merging it :)

**Comment by faragos** [comment]
Hey it's me again 😄
7.3 is out 🥳  Great release. 👍 
Can you give me a little bit more insight when you plan to review this PR? Because I would really need this feature.

**Comment by d80wrk** [comment]
How can we make this happen for 7.4?

**Comment by p2kmgcl** [comment]
Hey there!

First of all, sorry for the long (long long) time to have a look at this. Since we have updated the Toolkit a lot since this PR was opened and now we have a "build" step during the compress process. I have opened a new PR so we can continue the conversation there.

My idea is to tweak it if necessary to fit our needs and have it merged ASAP. I'll wait for your feedback :smile:  https://github.com/liferay/generator-liferay-fragments/pull/221

**Pull request closed without merging**
