### PR TITLE
build: Update to latest @liferay/npm-bundler

### PR DESCRIPTION
**Pull request by wincent**
We moved this from `liferay-npm-bundler` over to a named scope (`@liferay/npm-bundler`) and are currently [integrating this in DXP here](https://github.com/liferay-frontend/liferay-portal/pull/429).

Makes sense to update this everywhere, including the fragments toolkit as well.

### CODE REVIEW

**Comment by wincent** [comment]
@p2kmgcl: Would you please take a look at this? I don't know to test it. I tested the change in DXP, but that use case is a little different (ie. in `frontend-js-recharts`), so we shouldn't assume that this works without verifying first 😂

**Review by p2kmgcl — APPROVED** [review]

**Comment by p2kmgcl** [comment]
@wincent sorry, that's a (maybe random) permission issue we are having with Windows tests. I'm rerunning that job [here](https://travis-ci.org/github/liferay/generator-liferay-fragments/jobs/735789463) and should finish in a couple of minutes.

Anyway, I'll have a look manually, because I think that our tests don't cover that part yet.

**Comment by p2kmgcl** [comment]
I think I found a problem: we are calling npm-bundler [here](https://github.com/liferay/generator-liferay-fragments/blob/master/src/utils/project-content/build-project-content.ts#L24) using `npx liferay-npm-bundler` (because of not having a programmatic API for now), I guess we need to change that to `npx @liferay/npm-bundler` too. Is that right @wincent?

**Comment by wincent** [comment]
> I think I found a problem: we are calling npm-bundler [here](https://github.com/liferay/generator-liferay-fragments/blob/master/src/utils/project-content/build-project-content.ts#L24) using `npx liferay-npm-bundler` (because of not having a programmatic API for now), I guess we need to change that to `npx @liferay/npm-bundler` too. Is that right @wincent?

Ah yes. `npx liferay-npm-bundler` would run an old version, possibly pulling it down off the network, because you won't have any package of that name locally. `npx @liferay/npm-bundler` will run the newer, named-scope version. Note that the executable name hasn't changed (ie. the executable in the named-scope version is still called `liferay-npm-bundler`), but seeing as `npx` deals with package names and not executable names...

What's the advantage of using `npx` anyway? I've only ever used it for that "download-before-running-if-you-don't-already-have-it" use case. In your case, it seems like it might be quite sensitive to project environment (in terms of which version it ends up using). Are we sure it will chose the right one? I guess so. 🤷 

---

No hurry to merge this in any case @p2kmgcl. I might end up having to cut another release of the bundler today in order to solve some apparent issues on the DXP side that we're seeing in https://github.com/liferay-frontend/liferay-portal/pull/429

**Comment by wincent** [comment]
> I might end up having to cut another release of the bundler today in order to solve some apparent issues on the DXP side that we're seeing in [liferay-frontend/liferay-portal#429](https://github.com/liferay-frontend/liferay-portal/pull/429)

Or maybe not. I think CI was only failing there because [I am silly and didn't actually push the latest rev](https://github.com/liferay-frontend/liferay-portal/pull/429#issuecomment-708948013) before running the tests. 😂

**Comment by wincent** [comment]
I updated the `npx` call in dd9c596.

**Comment by p2kmgcl** [comment]
Maybe we should not be using `npx` there, but that's the only way I found to solve this: I want to run the `@liferay/npm-bundler@y` that is specified in `generator-liferay-fragments@x` dependency.

So now we have in generated projects package.json `generator-liferay-fragments@x, and in generator-liferay-fragments package.json `@liferay/npm-bundler@y`.

Do you now if there is a better way to do this? I thought about looking for the `node_modules/.bin/liferay-npm-bundler` file manually, I it looked a little fragile (I am not sure if that might change in different npm versions or if yarn creates that directory).

I now users might install an specific version of `@liferay/npm-bundler` and that would override our dependency, but that's a side effect that I think we can ignore.

**Comment by wincent** [comment]
> I now users might install an specific version of `@liferay/npm-bundler` and that would override our dependency, but that's a side effect that I think we can ignore.

Yeah, I think if somebody is going to install a specific version then it's on them to make sure it works for their use case.

I think using `npx` here is probably fine; it's just not something I'd seen used in this way before. At least you isolate yourself from platform differences, because it's supposedly going to do the right thing on Windows, Linux etc...

**Comment by p2kmgcl** [comment]
I tried to run this locally and I got a bundler error, I am sending this configuration:

```json
{
  "create-jar": false,
  "source": "src",
  "output": "build/liferay-npm-bundler-output",
  "workdir": "build/liferay-npm-bundler-workdir",
  "exports": {
    "sample-fragment": "./sample-collection/sample-fragment/main.js"
  },
  "imports": {
    "frontend-js-react-web": {
      "react": "*"
    }
  },
  "webpack": {
    "module": {
      "rules": [
        {
          "exclude": {},
          "test": {},
          "use": [
            {
              "loader": "babel-loader",
              "options": {
                "presets": [
                  "@babel/preset-env",
                  "@babel/preset-react"
                ]
              }
            }
          ]
        }
      ]
    }
  }
}
```

But it gives me this error:
```
❌ EntryModuleNotFoundError: Entry module not found: Error: Can't resolve 'build/liferay-npm-bundler-workdir/generated/sample-fragment.js' in '/home/p2kmgcl/Projects/ea/sample-liferay-fragments'
...at <unknown file>

❌ Build failed: webpack build finished with errors
```

The `build/liferay-npm-bundler-workdir/generated/sample-fragment.js` file actually exists. It looks like an issue we had (cc @izaera) before because we were using and old version of the bundler, but I checked the project dependencies and it's using `@liferay/npm-bundler@3.0.1-pre.0`, so that should be working.

Any clue? Maybe I need to make a pre-release to check this, because now I am `npm linking` and manually `npm installing` things to tests and I might be breaking something :shrug:

**Comment by wincent** [comment]
At first glance, not sure what might be causing that. The whole reason I cut 3.0.1-pre.0 was to fix errors that I was seeing in the prior release on integrating it into DXP; they were similar but different to the one you have.

For example I was seeing:

```
     [exec] ??? EntryModuleNotFoundError: Entry module not found: Error: Can't resolve './/opt/dev/projects/github/liferay-portal/modules/apps/frontend-js/frontend-js-recharts/build/node/bundler/bundler/generated/recharts.js' in '/opt/dev/projects/github/liferay-portal/modules/apps/frontend-js/frontend-js-recharts'
     [exec] ...at <unknown file>
```

Note the bad path starting with `.//opt/dev` which should obviously be `/opt/dev`. So that got fixed in https://github.com/liferay/liferay-frontend-projects/pull/156 by switching keeping the path absolute and not prepending the unwanted `./`.

Now, in your context, somehow, we _are_ seeing a relative path there, but it shouldn't make any difference because `build/liferay-npm-bundler-workdir/generated/sample-fragment.js` and `./build/liferay-npm-bundler-workdir/generated/sample-fragment.js` are the same file, for all intents and purposes. Maybe webpack disagrees though...

> Maybe I need to make a pre-release to check this, because now I am `npm linking` and manually `npm installing` things to tests and I might be breaking something

Maybe... 🤔 I have found `npm link` to be easily upset in DXP because Gradle comes along and destroys everything...

Can you tell me how to repro your local tests?

The [other PR sticking this version in `frontend-js-recharts` in DXP is green now](https://github.com/liferay-frontend/liferay-portal/pull/429), but I'd like to understand what's happening here better before calling that one "good".

**Comment by p2kmgcl** [comment]
Sure, these are normal steps:

1. Clone the repo :rainbow:
2. Install `yo` package locally
3. `npm link`
4. `yo liferay-fragments` to generate a sample project

Then `cd` to the project and (these are the _weird_ steps I followed):

5. Modify `src/sample-collection/sample-fragment/fragment.json` and change `"type"` to `"react"` (this way we force calling the bundler) when compressing.
6. I run `npm uninstall liferay-npm-bundler` and `npm install @liferay/npm-bundler` to be sure that `liferay-npm-bundler` does not exist, but probably just installing is fine.
7. `npm link generator-liferay-fragments`
8. `npm run compress` (will run `yo liferay-fragments:compress`, which calls the bundler as a build step).

You can check the generated configuration putting a console.log inside `liferay-npm-bundler.config.js`.

_*Edit_: if you can't/don't have time to reproduce this we can just merge and create a pre-release to be sure that we are testing with the correct bundler version, then iterate in another PR.

**Comment by wincent** [comment]
> _*Edit_: if you can't/don't have time to reproduce this we can just merge and create a pre-release to be sure that we are testing with the correct bundler version, then iterate in another PR.

There's really no hurry here. We aren't blocked by this PR going in or not — I simply want to update it to make sure we haven't broken anything. We have the algorithms session today but I will check out your repro steps at some point today and see what I can see.

**Comment by wincent** [comment]
Ok, I can repro and I think i have a solution. It is indeed that webpack wants either an absolute path or a `./`-prefixed relative path. It's going to reject anything of the form `build/blah/etc/...`.

I'll update the PR in a bit with a new version.

Also, running the generator creates this:

```
2414 directories, 18652 files
```

`#NodeLife`

**Comment by wincent** [comment]
Fix is up at https://github.com/liferay/liferay-frontend-projects/pull/160 — will cut a release once that's in and update.

**Comment by wincent** [comment]
Ok @p2kmgcl... I updated it with the new release and I think it works now... [see the test plan](https://github.com/liferay/generator-liferay-fragments/pull/167/commits/76f1caa2a88cc4fa4ef6bcfe25f91ed6f94c240b):

> 1. `npm link` repo.
> 2. In scratch directory, `yo liferay-fragments`.
> 3. `cd sample-liferay-fragments`.
> 4. `sed -i '' 's#"section"#"react"#' src/sample-collection/sample-fragment/fragment.json`.
> 5. `npm install @liferay/npm-bundler@3.0.1-pre.1`
> 6. `npm link generator-liferay-fragments`.
> 7. `npm run compress`.
> 8. See success message (eg. "build/liferay-fragments.zip file created" etc).

**Comment by p2kmgcl** [comment]
Alright, merging :musical_note:

**Pull request merged**
